docs(README): add deployment, run and project structure information
catenax/GPDM pull request #42
Opened 2022-03-17 16:54 UTC by nicoprow

2022-03-21 13:08 UTC, pazepaze requested changes

2022-03-21 13:08 UTC, pazepaze commented on README.md
> +obtaining a trustworthy certificate. When the Kubernetes cluster configured with these components, the application can be
"When the Kubernetes cluster configured" -> "When the Kubernetes cluster is configured"

2022-03-21 13:08 UTC, pazepaze commented on README.md
> +Private container registries my require authentication in order to be accessed. In this case the Helm deployment needs to
"Private container registries my require" -> "Private container registries may require"

2022-03-21 15:06 UTC, nicoprow commented on README.md
> +The local profile expects all enabled to components to be locally available on the host machine.
fixed

2022-03-21 15:07 UTC, nicoprow commented on README.md
> +Without the Elasticsearch component enabled the suggestions are always be empty and search requests will not filter any business partners.
fixed

2022-03-21 15:07 UTC, nicoprow commented on README.md
> +from the database. Where possible repositories should be defined as interfaces and auto-implemented by JPA. In cases when that is not
fixed

2022-03-21 15:07 UTC, nicoprow commented on README.md
> +When possible configuration classes, services and components should use configuration properties instead of accesses property values
fixed

2022-03-21 15:07 UTC, nicoprow commented on README.md
> +obtaining a trustworthy certificate. When the Kubernetes cluster configured with these components, the application can be
fixed

2022-03-22 07:49 UTC, pazepaze approved these changes

2022-03-22 08:49 UTC, merged