docs(OpenAPI): enhance OpenAPI descriptions for endpoints, request an…
catenax/GPDM pull request #43
Opened 2022-03-23 16:28 UTC by nicoprow

SpringDoc OpenAPI can't easily have custom schema names for generic types. In order to provide custom names the effort currently doesn't justify the benefit. That's why you will run across some strange names for some schemas there.

2022-03-28 11:23 UTC, pazepaze requested changes
the rest looks good

2022-03-28 11:23 UTC, pazepaze commented on src/main/kotlin/com/catenax/gpdm/dto/request/BusinessPartnerSearchRequest.kt
>      val classification: String?,
Swagger Annotation doesn't seem to work.
I think ```@field:Parameter(description = ...)``` needs to be used here.

2022-03-28 15:04 UTC, nicoprow commented on src/main/kotlin/com/catenax/gpdm/dto/request/BusinessPartnerSearchRequest.kt
>      val classification: String?,
Right, with the @field they would be visible, but actually those classes will be covered in pull request #40 as well. So I just deleted the annotations for now as those classes have additional problems: @ParameterObject is not working here for example as well. Fixes for that are being taken care of in #40 .

2022-03-30 08:36 UTC, pazepaze reviewed
As we discussed in the daily, you wanted to think about the sonar motivated changes

2022-03-30 09:18 UTC, pazepaze approved these changes

2022-03-30 09:18 UTC, nicoprow commented
Removed OpenApi descriptions from the values again as discussed. But reduced a bit of duplication by introducing a constant holding identical descriptions.

2022-03-30 09:24 UTC, merged